server:
  port: 8650
spring:
  application:
    name: WEITEST
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cathaybk?allowMultiQueries=true&useSSL=false&characterEncoding=utf8
    username: root
    password: qwe123456qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true